// X11 atoms 1..68 are predefined and have universal names. Any atom ID a
// client sees with a value in this range (without ever calling InternAtom) is
// known to be one of these. Server-assigned atoms (from InternAtom) start at
// 69 and have implementation-defined values.

public func predefinedAtomName(_ atom: UInt32) -> String? {
    switch atom {
    case 1:  return "PRIMARY"
    case 2:  return "SECONDARY"
    case 3:  return "ARC"
    case 4:  return "ATOM"
    case 5:  return "BITMAP"
    case 6:  return "CARDINAL"
    case 7:  return "COLORMAP"
    case 8:  return "CURSOR"
    case 9:  return "CUT_BUFFER0"
    case 10: return "CUT_BUFFER1"
    case 11: return "CUT_BUFFER2"
    case 12: return "CUT_BUFFER3"
    case 13: return "CUT_BUFFER4"
    case 14: return "CUT_BUFFER5"
    case 15: return "CUT_BUFFER6"
    case 16: return "CUT_BUFFER7"
    case 17: return "DRAWABLE"
    case 18: return "FONT"
    case 19: return "INTEGER"
    case 20: return "PIXMAP"
    case 21: return "POINT"
    case 22: return "RECTANGLE"
    case 23: return "RESOURCE_MANAGER"
    case 24: return "RGB_COLOR_MAP"
    case 25: return "RGB_BEST_MAP"
    case 26: return "RGB_BLUE_MAP"
    case 27: return "RGB_DEFAULT_MAP"
    case 28: return "RGB_GRAY_MAP"
    case 29: return "RGB_GREEN_MAP"
    case 30: return "RGB_RED_MAP"
    case 31: return "STRING"
    case 32: return "VISUALID"
    case 33: return "WINDOW"
    case 34: return "WM_COMMAND"
    case 35: return "WM_HINTS"
    case 36: return "WM_CLIENT_MACHINE"
    case 37: return "WM_ICON_NAME"
    case 38: return "WM_ICON_SIZE"
    case 39: return "WM_NAME"
    case 40: return "WM_NORMAL_HINTS"
    case 41: return "WM_SIZE_HINTS"
    case 42: return "WM_ZOOM_HINTS"
    case 43: return "MIN_SPACE"
    case 44: return "NORM_SPACE"
    case 45: return "MAX_SPACE"
    case 46: return "END_SPACE"
    case 47: return "SUPERSCRIPT_X"
    case 48: return "SUPERSCRIPT_Y"
    case 49: return "SUBSCRIPT_X"
    case 50: return "SUBSCRIPT_Y"
    case 51: return "UNDERLINE_POSITION"
    case 52: return "UNDERLINE_THICKNESS"
    case 53: return "STRIKEOUT_ASCENT"
    case 54: return "STRIKEOUT_DESCENT"
    case 55: return "ITALIC_ANGLE"
    case 56: return "X_HEIGHT"
    case 57: return "QUAD_WIDTH"
    case 58: return "WEIGHT"
    case 59: return "POINT_SIZE"
    case 60: return "RESOLUTION"
    case 61: return "COPYRIGHT"
    case 62: return "NOTICE"
    case 63: return "FONT_NAME"
    case 64: return "FAMILY_NAME"
    case 65: return "FULL_NAME"
    case 66: return "CAP_HEIGHT"
    case 67: return "WM_CLASS"
    case 68: return "WM_TRANSIENT_FOR"
    default: return nil
    }
}
